apiVersion: v1
data:
  credential: TXlTZWN1cmVQQHNz
kind: Secret
metadata:
  creationTimestamp: "2019-12-01T20:35:09Z"
  name: secret-creds
  namespace: default
  resourceVersion: "5704655"
  selfLink: /api/v1/namespaces/default/secrets/secret-creds
  uid: 11567a43-147a-11ea-b98d-42010a80021f
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: vlm
      mountPath: /app-creds
  volumes:
  - name: vlm
    secret:
      secretName: secret-creds
