---
apiVersion: v1
data:
  credential: TXlTZWN1cmVQQHNz
kind: Secret
metadata:
  creationTimestamp: "2019-12-01T20:59:05Z"
  name: mysql-credentials
  namespace: default
  resourceVersion: "5709460"
  selfLink: /api/v1/namespaces/default/secrets/mysql-credentials
  uid: 6905d518-147d-11ea-b98d-42010a80021f
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: credential
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: db-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
  type: ClusterIp
status:
  loadBalancer: {}
